title: Anti-Money Laundering / Countering the Financing of Terrorism Division
title-abbreviated: MinLaw - ACD
description: >- # this means to ignore newlines until "baseurl:"
  ACD is a Division in the Ministry of Law in charge of supervising the precious stones and precious metals sector and mitigating Singapore's exposure to ML/TF risks.
url: "https://mlaw-acd-prototype.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: isomerpages/isomerpages-template
safe: false

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap

# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Resource Room and Pagination
paginate: 12

# Homepage sections
homepage_hero_i_want_to: false
homepage_resources: false

# Feedback Form URL
feedback_form_url: "https://www.mlaw.gov.sg/eservices/enquiry/"

# FAQ URL
faq_url: "https://va.ecitizen.gov.sg/cfp/customerPages/mlaw/explorefaq.aspx"
faq_url_external: false

# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"


collections:
  information-for-regulated-dealers:
    output: true
resources_name: events
